import React, { useEffect, useState } from 'react';
import AdminSidebar from '../../components/AdminSidebar';
import NoticeDetailModal from '../../components/NoticeDetailModal';
import { getAllNotices, getSignatureBase64 } from '../../services/authService';
import { downloadNoticePdf } from '../../utils/noticePdf';

function Notices() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [selected, setSelected] = useState(null);
  const [busy, setBusy] = useState(null);

  useEffect(() => {
    (async () => {
      try {
        const r = await getAllNotices();
        setItems(r.data || []);
      } catch (e) { console.error(e); }
      finally { setLoading(false); }
    })();
  }, []);

  const download = async (notice) => {
    setBusy(notice.id);
    try {
      const [s, sh, oi] = await Promise.all([
        notice.staffSignatureImage ? getSignatureBase64(notice.staffSignatureImage).catch(() => null) : null,
        notice.sectionHeadSignatureImage ? getSignatureBase64(notice.sectionHeadSignatureImage).catch(() => null) : null,
        notice.officeInchargeSignatureImage ? getSignatureBase64(notice.officeInchargeSignatureImage).catch(() => null) : null,
      ]);
      downloadNoticePdf(notice, { staff: s, sh, oi });
    } catch {
      alert('Could not generate PDF.');
    } finally {
      setBusy(null);
    }
  };

  const filtered = items.filter(n => {
    if (search && !n.referenceNumber?.toLowerCase().includes(search.toLowerCase())) return false;
    if (typeFilter && n.noticeType !== typeFilter) return false;
    return true;
  });

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: '#eef4ff' }}>
      <AdminSidebar />
      <div style={{ flex: 1, marginLeft: 250, padding: 30 }}>
        <h1 style={{ color: '#0b2e6f', marginBottom: 4 }}>Leave Notices</h1>
        <p style={{ color: '#5b7bab', marginTop: 0 }}>
          All approval / rejection notices generated by the system. Click any row to view full details.
        </p>

        <div style={{ background: '#fff', padding: 14, borderRadius: 12, display: 'flex', gap: 12, marginTop: 18, marginBottom: 18 }}>
          <input placeholder="Search by reference no."
            value={search} onChange={e => setSearch(e.target.value)} style={inp} />
          <select value={typeFilter} onChange={e => setTypeFilter(e.target.value)} style={inp}>
            <option value="">All types</option>
            <option value="APPROVAL">Approval</option>
            <option value="REJECTION">Rejection</option>
          </select>
        </div>

        <div style={{ background: '#fff', padding: 20, borderRadius: 14 }}>
          {loading ? <p>Loading...</p> :
            filtered.length === 0 ? (
              <p style={{ color: '#888', textAlign: 'center', padding: 30 }}>No notices found.</p>
            ) : (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
                <thead>
                  <tr style={{ background: '#f8fafc' }}>
                    <th style={th}>Ref</th>
                    <th style={th}>Type</th>
                    <th style={th}>Decision By</th>
                    <th style={th}>Date</th>
                    <th style={th}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map(n => (
                    <tr key={n.id}
                      onClick={() => setSelected(n)}
                      onMouseEnter={e => e.currentTarget.style.background = '#f8fafc'}
                      onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                      style={{ borderBottom: '1px solid #eee', cursor: 'pointer' }}>
                      <td style={{ ...td, fontSize: 12, color: '#0d6efd', fontWeight: 700 }}>{n.referenceNumber}</td>
                      <td style={td}><TypePill type={n.noticeType} /></td>
                      <td style={td}>{n.finalDecisionByRole}</td>
                      <td style={td}>{new Date(n.createdAt).toLocaleString()}</td>
                      <td style={td} onClick={e => e.stopPropagation()}>
                        <button onClick={() => setSelected(n)} style={{ ...actionBtn, background: '#f1f5f9', color: '#0b2e6f', marginRight: 6 }}>
                          View
                        </button>
                        <button onClick={() => download(n)} disabled={busy === n.id} style={actionBtn}>
                          {busy === n.id ? '...' : '📄 PDF'}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )
          }
        </div>

        {selected && (
          <NoticeDetailModal
            notice={selected}
            onClose={() => setSelected(null)}
            onDownloadPdf={download}
          />
        )}
      </div>
    </div>
  );
}

function TypePill({ type }) {
  const ok = type === 'APPROVAL';
  return <span style={{
    padding: '4px 10px', borderRadius: 20, fontSize: 11, fontWeight: 700,
    background: ok ? '#d1fae5' : '#fee2e2',
    color: ok ? '#065f46' : '#991b1b',
    whiteSpace: 'nowrap',
  }}>{type}</span>;
}

const th = { padding: 12, textAlign: 'left', fontSize: 13, color: '#334155', fontWeight: 700 };
const td = { padding: 12, color: '#0b2e6f' };
const inp = { padding: '9px 12px', borderRadius: 8, border: '1px solid #cbd5e1', fontSize: 13, background: '#fff', minWidth: 240, boxSizing: 'border-box' };
const actionBtn = { padding: '6px 14px', background: '#0d6efd', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 12, fontWeight: 600 };

export default Notices;